// Generated by synth-next-template.mjs from db_schema.json
// Schema metadata + data-access helpers. Re-run the generator to refresh.

export type FieldDef = {
  name: string;
  type: string;
  required?: boolean;
  unique?: boolean;
  fk?: string;
  relationTarget?: string;
  options?: { values?: string[] };
};

export type CollectionMeta = {
  name: string;
  model: string;
  accessor: string;
  label: string;
  auth: boolean;
  presentable: string;
  rules: { list: string; view: string; create: string; update: string; delete: string };
  fields: FieldDef[];
};

const COLLECTIONS: Record<string, CollectionMeta> = {
  "users": {
    "name": "users",
    "model": "User",
    "accessor": "user",
    "label": "Users",
    "auth": true,
    "presentable": "email",
    "rules": {
      "list": "",
      "view": "",
      "create": "",
      "update": "",
      "delete": ""
    },
    "fields": [
      {
        "name": "email",
        "type": "email",
        "required": true,
        "unique": true
      },
      {
        "name": "password",
        "type": "text",
        "required": true
      },
      {
        "name": "name",
        "type": "text",
        "required": false
      },
      {
        "name": "role",
        "type": "select",
        "required": false,
        "options": {
          "values": [
            "customer",
            "admin"
          ]
        }
      },
      {
        "name": "phone",
        "type": "text",
        "required": false
      },
      {
        "name": "address",
        "type": "text",
        "required": false
      }
    ]
  },
  "pages": {
    "name": "pages",
    "model": "Page",
    "accessor": "page",
    "label": "Pages",
    "auth": false,
    "presentable": "title",
    "rules": {
      "list": "status = \"published\"",
      "view": "status = \"published\"",
      "create": "@request.auth.role = \"admin\"",
      "update": "@request.auth.role = \"admin\"",
      "delete": "@request.auth.role = \"admin\""
    },
    "fields": [
      {
        "name": "title",
        "type": "text",
        "required": true
      },
      {
        "name": "slug",
        "type": "text",
        "required": true,
        "unique": true
      },
      {
        "name": "content",
        "type": "text",
        "required": false
      },
      {
        "name": "status",
        "type": "select",
        "required": true,
        "options": {
          "values": [
            "published",
            "draft",
            "archived"
          ]
        }
      }
    ]
  },
  "contacts": {
    "name": "contacts",
    "model": "Contact",
    "accessor": "contact",
    "label": "Contacts",
    "auth": false,
    "presentable": "name",
    "rules": {
      "list": "user = @request.auth.id",
      "view": "user = @request.auth.id",
      "create": "@request.auth.id != \"\"",
      "update": "@request.auth.role = \"admin\"",
      "delete": "@request.auth.role = \"admin\""
    },
    "fields": [
      {
        "name": "user",
        "type": "relation",
        "required": false,
        "fk": "userId",
        "relationTarget": "users"
      },
      {
        "name": "name",
        "type": "text",
        "required": true
      },
      {
        "name": "email",
        "type": "text",
        "required": true
      },
      {
        "name": "message",
        "type": "text",
        "required": true
      },
      {
        "name": "status",
        "type": "select",
        "required": true,
        "options": {
          "values": [
            "new",
            "replied",
            "closed"
          ]
        }
      }
    ]
  },
  "settings": {
    "name": "settings",
    "model": "Setting",
    "accessor": "setting",
    "label": "Settings",
    "auth": false,
    "presentable": "name",
    "rules": {
      "list": "",
      "view": "",
      "create": "@request.auth.role = \"admin\"",
      "update": "@request.auth.role = \"admin\"",
      "delete": "@request.auth.role = \"admin\""
    },
    "fields": [
      {
        "name": "name",
        "type": "text",
        "required": true
      },
      {
        "name": "tagline",
        "type": "text",
        "required": false
      },
      {
        "name": "footerText",
        "type": "text",
        "required": false
      }
    ]
  }
};

export const AUTH = { collection: "users", accessor: "user" } as const;
// ---- Schema helpers (static fragment, concatenated by the generator) ----
// These functions reference the module-level `COLLECTIONS` and `AUTH`
// constants that are generated above this fragment.

export function getCollection(name: string): CollectionMeta | undefined {
  return COLLECTIONS[name];
}

export function baseCollections(): CollectionMeta[] {
  return Object.values(COLLECTIONS).filter((c) => !c.auth);
}

export type AuthScope = "public" | "any" | "admin" | "owner";

/**
 * Translate a PocketBase-style access rule into a coarse authorization scope.
 * This is a pragmatic heuristic for generated templates; refine per project.
 */
export function authorize(
  rule: string | undefined,
  _payload: { role?: string } | null
): AuthScope {
  const r = (rule || "").trim();
  if (r === "") return "public";
  const adminOnly = r.includes('@request.auth.role = "admin"');
  const owner = r.includes("= @request.auth.id");
  const anyAuth = r.includes('@request.auth.id != ""');
  if (adminOnly && !owner && !anyAuth) return "admin";
  if (owner) return "owner";
  if (anyAuth) return "any";
  return "admin";
}

export function ownerField(
  name: string
): { field: string; fk: string } | null {
  const meta = COLLECTIONS[name];
  if (!meta) return null;
  const f = meta.fields.find(
    (f) => f.type === "relation" && f.relationTarget === AUTH.collection
  );
  if (!f) return null;
  return { field: f.name, fk: f.fk || f.name + "Id" };
}

export function coerceInput(
  name: string,
  body: Record<string, unknown>,
  opts: { partial?: boolean } = {}
): Record<string, unknown> {
  const meta = COLLECTIONS[name];
  if (!meta) return {};
  const out: Record<string, unknown> = {};
  for (const f of meta.fields) {
    if (f.name === "id" || f.name === "created" || f.name === "updated") continue;
    if (f.type === "relation") {
      const fk = f.fk || f.name + "Id";
      let v: unknown = body[fk] ?? body[f.name];
      if (v === "" || v === undefined) v = null;
      if (v !== null || !opts.partial) out[fk] = v === null ? null : String(v);
      continue;
    }
    let v: unknown = body[f.name];
    if (v === undefined && opts.partial) continue;
    if (v === "" || v === undefined) v = null;
    switch (f.type) {
      case "number":
        out[f.name] = v === null ? null : Number(v);
        break;
      case "bool":
        out[f.name] = v === null ? null : Boolean(v);
        break;
      case "date":
        out[f.name] = v === null ? null : new Date(String(v));
        break;
      case "json":
        out[f.name] = v === null ? null : typeof v === "string" ? v : JSON.stringify(v);
        break;
      case "file":
        out[f.name] = v === null ? null : Array.isArray(v) ? JSON.stringify(v) : String(v);
        break;
      default:
        out[f.name] = v === null ? null : String(v);
    }
  }
  return out;
}
